name: Build DynamicJobsEconomy

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    name: Build (matrix)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [ default, spigot-lite, spigot-ultra, spigot-ultra-mysql, spigot-linux-sqlite ]
    env:
      # Optional: set to a byte value (e.g., 4000000) to enforce a max artifact size per job
      MAX_JAR_SIZE: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven (unit tests)
        shell: bash
        run: |
          if [ "${{ matrix.profile }}" = "default" ]; then
            mvn -B -DskipTests=false package
          else
            mvn -B -P ${{ matrix.profile }} -DskipTests=false package
          fi

      - name: Record JAR size
        id: size
        shell: bash
        run: |
          JAR=$(ls -1 target/DynamicJobsEconomy-*.jar | head -n1)
          if [ -z "$JAR" ]; then
            echo "No JAR found in target/"
            exit 1
          fi
          SIZE=$(stat -c%s "$JAR")
          echo "Built: $JAR ($SIZE bytes)"
          echo "jar_path=$JAR" >> $GITHUB_OUTPUT
          echo "jar_size=$SIZE" >> $GITHUB_OUTPUT

      - name: Enforce size guard
        if: env.MAX_JAR_SIZE != ''
        shell: bash
        run: |
          if [ "${{ steps.size.outputs.jar_size }}" -gt "${{ env.MAX_JAR_SIZE }}" ]; then
            echo "Artifact too large: ${{ steps.size.outputs.jar_size }} > ${{ env.MAX_JAR_SIZE }}"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DynamicJobsEconomy-jar-${{ matrix.profile }}
          path: ${{ steps.size.outputs.jar_path }}
          if-no-files-found: error

  integration-tests:
    name: Integration Tests (Testcontainers)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run database integration tests (Testcontainers)
        run: mvn -B -P integration-tests -DskipTests=false test
