name: Build DynamicJobsEconomy

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DynamicJobsEconomy-jar
          path: |
            target/*.jar
          if-no-files-found: error
